-- RADAR IA — BANCO SUPABASE
create extension if not exists pgcrypto;

create table if not exists products (
  id uuid primary key default gen_random_uuid(),
  provider text not null default 'mercadolivre',
  external_id text not null,
  title text not null,
  permalink text not null,
  image_url text,
  category_id text,
  seller_id text,
  seller_reputation text,
  rating numeric,
  review_count integer not null default 0,
  sold_quantity integer not null default 0,
  available_quantity integer not null default 0,
  free_shipping boolean not null default false,
  condition text,
  current_price numeric not null default 0,
  original_price numeric,
  discount_percentage integer not null default 0,
  score integer not null default 0,
  score_breakdown jsonb not null default '{}'::jsonb,
  recommendation text,
  last_seen_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(provider, external_id)
);

create table if not exists price_history (
  id bigint generated by default as identity primary key,
  product_id uuid not null references products(id) on delete cascade,
  price numeric not null,
  original_price numeric,
  discount_percentage integer not null default 0,
  collected_at timestamptz not null default now()
);
create index if not exists price_history_product_date_idx on price_history(product_id, collected_at desc);

create table if not exists watchlist (
  id uuid primary key default gen_random_uuid(),
  product_id uuid references products(id) on delete set null,
  provider text not null default 'mercadolivre',
  external_id text not null,
  title text not null,
  permalink text not null,
  image_url text,
  last_price numeric,
  last_checked_at timestamptz,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  unique(provider, external_id)
);

create table if not exists search_runs (
  id bigint generated by default as identity primary key,
  query text not null,
  result_count integer not null default 0,
  status text not null default 'running',
  started_at timestamptz not null default now(),
  finished_at timestamptz
);

create table if not exists publications (
  id uuid primary key default gen_random_uuid(),
  product_external_id text,
  channel text not null,
  content text not null,
  affiliate_url text,
  status text not null default 'draft',
  created_at timestamptz not null default now(),
  published_at timestamptz
);

create table if not exists app_settings (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);

insert into app_settings(key,value)
values ('score_weights','{"rating":25,"volume":25,"discount":25,"shipping":15,"seller":10,"min_score":55}'::jsonb)
on conflict (key) do nothing;

create table if not exists integrations (
  provider text primary key,
  access_token text,
  refresh_token text,
  user_id text,
  expires_in integer,
  active boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists oauth_states (
  state text primary key,
  code_verifier text not null,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

-- O frontend não acessa essas tabelas diretamente no MVP.
-- O backend usa a chave secreta e ignora RLS.
alter table products enable row level security;
alter table price_history enable row level security;
alter table watchlist enable row level security;
alter table search_runs enable row level security;
alter table publications enable row level security;
alter table app_settings enable row level security;
alter table integrations enable row level security;
alter table oauth_states enable row level security;
